name = "alainpaluku-site"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-04-24"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SESSION"
id = "00ac4eee994442b8ac4814cd2efb212e"
